# auto-start tmux, if its not already set in the ENV, this is useful to disable tmux in VSCode by overwriting the env
# ZSH_TMUX_AUTOSTART=${ZSH_TMUX_AUTOSTART:="true"}
# ZSH_TMUX_AUTOSTART_ONCE="true"

# do not close terminal when tmux exits
ZSH_TMUX_AUTOQUIT="false"

# set EDITOR for git diff etc...
export EDITOR='nvim'

# set BAT theme for syntax highlighting
# export BAT_THEME="Dracula"

# Source aliases from ~/.aliases
source $HOME/.aliases

# Extend path to include .bin directory
export PATH=$PATH:~/.bin

##install thefuck
#eval $(thefuck --alias)

# Set any secrets defined in .secrets
if [ -f $HOME/.secrets/keys ]; then
   source $HOME/.secrets/keys
fi


# Set higher filewatcher limit
# launchctl limit maxfiles 65535 200000
# ulimit -Sn 65535

# Make fzf respect .gitignore
# export FZF_DEFAULT_COMMAND="rg --files --hidden --glob '!.git/'"
# export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS'
# --color=dark
# --color=fg:-1,bg:-1,hl:#5fff87,fg+:-1,bg+:-1,hl+:#ffaf5f
# --color=info:#af87ff,prompt:#5fff87,pointer:#ff87d7,marker:#ff87d7,spinner:#ff87d7
# '

# ------- oh-my-zsh config:

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="dracula"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=7

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
ZSH_CUSTOM=~/.oh-my-zsh-custom

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(
  git
  command-not-found
  docker
  github
  macos
  brew
  extract
  npm
  tmux
  vscode
  z
  history-substring-search
  zsh-syntax-highlighting
)
# fzf

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
if [[ -n $SSH_CONNECTION ]]; then
  export EDITOR='vim'
else
  export EDITOR='nvim'
fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

# iTerm2 Integration
# test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# [ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# tabtab source for packages
# uninstall by removing these lines
# [[ -f ~/.config/tabtab/__tabtab.zsh ]] && . ~/.config/tabtab/__tabtab.zsh || true

# Turn on starship prompt
eval "$(starship init zsh)"

alias ls='eza --icons'
alias lsa='eza --icons -lA -sd'
alias lss='eza --icons -A -sd -gs'

## McFly (a better ctrl-r)
eval "$(mcfly init zsh)"

# ## Zoxide (a better cd)
# eval "$(zoxide init zsh)"


# . /opt/homebrew/opt/asdf/libexec/asdf.sh

export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
# export PATH=$(pyenv root)/shims:$PATH

# Apple JDK stuffz
# Disable jdk11, who needs it anymore...
# alias jdk11='export JAVA_HOME=`/usr/libexec/java_home -v 11`'
export JAVA_HOME=`/usr/libexec/java_home -v 17`

# GitHub Co-Pilot CLI
# eval "$(github-copilot-cli alias -- "$0")"

# Activate mise (asdf replacement)
eval "$(~/.local/bin/mise activate zsh)"
